pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: main, url: 'https://github.com/pikkilichakri/Expense_Docker_Project.git'
            }
        }

        stage('Terraform') {
            steps {
                // Inject AWS creds only for this block
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh '''
                        cd AMAZON_INFRA_DEPLOYMENT/terraform
                        terraform init
                        terraform validate
                        terraform plan
                        terraform $action --auto-approve
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t expense-app AMAZON_INFRA_DEPLOYMENT/
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                    # Remove any existing container
                    if [ $(docker ps -aq -f name=expense-app) ]; then
                        docker rm -f expense-app
                    fi
                    # Run the new container
                    docker run -d --name expense-app -p 9091:80 expense-app
                '''
            }
        }
    }
}
