pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials("aws-access-key-id")
        AWS_SECRET_ACCESS_KEY_ID = credentials("aws-secret-key-id")
    }

    stages {
        stage('Init Terraform') {
            steps {
                sh '''
                    cd AMAZON_INFRA_DEPLOYMENT/terraform
                    terraform init
                '''
            }
        }

        stage('Apply Terraform') {
            steps {
                sh '''
                    cd AMAZON_INFRA_DEPLOYMENT/terraform
                    terraform apply -auto-approve
                '''
            }
        }

        stage('Show Public IP') {
            steps {
                sh '''
                    cd AMAZON_INFRA_DEPLOYMENT/terraform
                    terraform output web_server_ip
                '''
            }
        }
    }
}
